import test from 'node:test';
import assert from 'node:assert/strict';
import {parseShopifyStatus} from '../src/lib/connections/shopifyStatus.ts';
const storeId='90000000-0000-4000-8000-000000000004';
const attempt={state:'completed',startedAt:'2026-09-17T12:00:00.000Z',finishedAt:'2026-09-17T12:01:00.000Z',from:'2026-09-17',to:'2026-09-17',resultCode:'replay'};
const fixture=()=>({state:'available',storeId,latestAttempt:attempt,latestSuccessfulCollection:attempt,candidate:{state:'needs_recheck',from:attempt.from,to:attempt.to,orderCount:1,refundCount:2,mappedEventCount:0,testExcludedCount:1},financialVerification:'not_assessed'});
test('safe scoped projection retains genuine zero, strips raw data and never claims financial verification',()=>{const value=parseShopifyStatus({...fixture(),secret:'hidden',payload:{email:'private@example.com'}},storeId);assert.equal(value.candidate.mappedEventCount,0);assert.equal(value.candidate.state,'needs_recheck');assert.equal(value.financialVerification,'not_assessed');assert.doesNotMatch(JSON.stringify(value),/hidden|private@example/);});
test('wrong store, mismatched period, malformed counts and unsupported completion fail closed',()=>{for(const value of [{...fixture(),storeId:'another'},{...fixture(),candidate:{...fixture().candidate,from:'2026-08-17'}},{...fixture(),candidate:{...fixture().candidate,orderCount:-1}},{...fixture(),latestSuccessfulCollection:{...attempt,resultCode:'stale_source'}},{...fixture(),latestAttempt:{...attempt,finishedAt:null}},{...fixture(),financialVerification:'verified'}])assert.throws(()=>parseShopifyStatus(value,storeId),/unavailable/);});
test('no history and unknown counts are distinct from completed zero',()=>{const result=parseShopifyStatus({state:'not_configured',storeId,latestAttempt:null,candidate:{state:'not_assessed'},financialVerification:'not_assessed'},storeId);assert.equal(result.latestAttempt,null);assert.equal(result.latestSuccessfulCollection,null);assert.equal(result.candidate.orderCount,null);});
