import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {createXeroSavedMappingRouter} from '../src/routes/xero-saved-mapping.ts';
import {createXeroSavedMappingRuntime} from '../src/lib/xero-saved-mapping-runtime.ts';
const store='11111111-1111-4111-8111-111111111111',value={storeId:store,state:'mapping_unavailable',mapping:null};
async function server(deps,run){const app=express();app.use('/api/xero',createXeroSavedMappingRouter(deps));const instance=await new Promise(resolve=>{const v=app.listen(0,'127.0.0.1',()=>resolve(v));});try{await run(`http://127.0.0.1:${instance.address().port}/api/xero/saved-mapping`);}finally{await new Promise(resolve=>instance.close(resolve));}}
test('saved metadata route defaults off and rejects missing bearer or expanded store request',async()=>{await server({},async url=>assert.equal((await fetch(`${url}?storeId=${store}`)).status,503));const calls=[];await server({authenticate:async token=>{calls.push(token);return {userId:'verified'};},read:async(identity,id)=>{calls.push({identity,id});return value;}},async url=>{assert.equal((await fetch(`${url}?storeId=${store}`)).status,401);const headers={authorization:'Bearer valid'};assert.equal((await fetch(`${url}?storeId=${store}&tenantId=untrusted`,{headers})).status,400);const res=await fetch(`${url}?storeId=${store}`,{headers});assert.equal(res.status,200);assert.equal(res.headers.get('cache-control'),'private, no-store');assert.deepEqual(await res.json(),value);});assert.deepEqual(calls,['Bearer valid',{identity:{userId:'verified'},id:store}]);});
test('metadata errors and cross-store replies expose no directory, user or credential details',async()=>{for(const deps of [{authenticate:async()=>{throw Error('private token');},read:async()=>value},{authenticate:async()=>({userId:'verified'}),read:async()=>({...value,storeId:'22222222-2222-4222-8222-222222222222'})}])await server(deps,async url=>{const res=await fetch(`${url}?storeId=${store}`,{headers:{authorization:'Bearer valid'}});assert.ok([403,503].includes(res.status));assert.doesNotMatch(await res.text(),/private|token|22222222/);});});
const env={NIGHT_SCOUT_XERO_SAVED_MAPPING_ENABLED:'true',NIGHT_SCOUT_RUNTIME_ENV:'staging',NIGHT_SCOUT_XERO_STAGING_PROJECT_REF:'bioalckltvkhlczusdvl',VITE_SUPABASE_URL:'https://bioalckltvkhlczusdvl.supabase.co',VITE_SUPABASE_ANON_KEY:'synthetic-public-key-material'};
const createAuthClient=()=>({auth:{getUser:async()=>({data:{user:{id:'verified-user'}},error:null})}});
test('authentication fetch has a timeout signal and preserves incoming cancellation',async()=>{
 let authOptions,signal;
 createXeroSavedMappingRuntime(env,{createAuthClient:(_url,_key,options)=>{authOptions=options;return createAuthClient();},fetchImpl:async(_url,options)=>{signal=options.signal;return new Response('{}');}});
 await authOptions.global.fetch(env.VITE_SUPABASE_URL+'/auth/v1/user');
 assert.ok(signal instanceof AbortSignal);assert.equal(signal.aborted,false);
 const cancelled=new AbortController();cancelled.abort();
 await authOptions.global.fetch(env.VITE_SUPABASE_URL+'/auth/v1/user',{signal:cancelled.signal});
 assert.equal(signal.aborted,true);
});
test('metadata runtime fixed staging member bearer only with one-use identity and streaming bounds',async()=>{let call;const runtime=createXeroSavedMappingRuntime(env,{createAuthClient,fetchImpl:async(url,options)=>{call={url,options};return new Response(JSON.stringify(value));}});const identity=await runtime.authenticate('Bearer synthetic');assert.deepEqual(await runtime.read(identity,store),value);assert.equal(call.url,env.VITE_SUPABASE_URL+'/rest/v1/rpc/xero_saved_mapping');assert.deepEqual(JSON.parse(call.options.body),{p_store_id:store});assert.equal(call.options.headers.authorization,'Bearer synthetic');await assert.rejects(runtime.read(identity,store));assert.equal(createXeroSavedMappingRuntime({}),undefined);assert.throws(()=>createXeroSavedMappingRuntime({...env,NIGHT_SCOUT_RUNTIME_ENV:'production'}));for(const response of [()=>new Response('x'.repeat(131_073)),()=>new Response('{}',{status:404})]){const r=createXeroSavedMappingRuntime(env,{createAuthClient,fetchImpl:async()=>response()});await assert.rejects(r.read(await r.authenticate('Bearer synthetic'),store));}});
