import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {parseXeroAccountingPeriod} from '../src/lib/xero-accounting-reader.ts';
import {createXeroAccountingRouter} from '../src/routes/xero-accounting.ts';
import {createXeroAccountingRuntime} from '../src/lib/xero-accounting-runtime.ts';
const scope={storeId:'11111111-1111-4111-8111-111111111111',from:'2026-09-01',to:'2026-09-25',currency:'GBP'};
const value={storeId:scope.storeId,scope:{from:scope.from,to:scope.to,currency:scope.currency},state:'available',reason:null,accounting:{basis:'accrual_p_and_l',currency:'GBP',asOf:'2026-09-25',retrievedAt:'2026-09-25T12:00:00Z',mappingVersionId:'22222222-2222-4222-8222-222222222222',closedPeriod:false,bookedRevenueMinor:'8600',processingFeesMinor:'-300',advertisingMinor:'-2000',softwareMinor:'-5000'},cash:null,shopifyComparison:'not_requested'};
test('exact accounting scope preserves signed minor units and rejects blended, cash, precision or provenance expansion',()=>{assert.deepEqual(parseXeroAccountingPeriod(value,scope),value);const retained={...value,state:'stale',reason:'source_refresh_failed',accounting:{...value.accounting,closedPeriod:true}};assert.deepEqual(parseXeroAccountingPeriod(retained,scope),retained);assert.equal(parseXeroAccountingPeriod({...retained,accounting:value.accounting},scope),null);for(const bad of [{...value,cash:{includedCash:123}},{...value,shopifyComparison:'compared'},{...value,scope:{...value.scope,to:'2026-09-30'}},{...value,accounting:{...value.accounting,asOf:'2026-09-24'}},{...value,accounting:{...value.accounting,bookedRevenueMinor:'9007199254740992'}},{...value,accounting:{...value.accounting,bookedRevenueMinor:8600}},{...value,accounting:{...value.accounting,rawReport:{}}}])assert.equal(parseXeroAccountingPeriod(bad,scope),null);const unavailable={...value,state:'unavailable',reason:'source_refresh_failed',accounting:null};assert.deepEqual(parseXeroAccountingPeriod(unavailable,scope),unavailable);assert.equal(parseXeroAccountingPeriod({...unavailable,accounting:value.accounting},scope),null);});
async function server(deps,run){const app=express();app.use('/api/xero',createXeroAccountingRouter(deps));const instance=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});try{await run(`http://127.0.0.1:${instance.address().port}/api/xero/accounting-period`);}finally{await new Promise(resolve=>instance.close(resolve));}}
test('amount route default off, exact scope and authenticated identity required',async()=>{const query=new URLSearchParams(scope),headers={authorization:'Bearer valid'},calls=[];await server({},async url=>assert.equal((await fetch(`${url}?${query}`,{headers})).status,503));await server({authenticate:async token=>{calls.push(token);return {userId:'verified'};},read:async(identity,input)=>{calls.push({identity,input});return value;}},async url=>{assert.equal((await fetch(`${url}?${query}`)).status,401);assert.equal((await fetch(`${url}?${query}&extra=1`,{headers})).status,400);const response=await fetch(`${url}?${query}`,{headers});assert.equal(response.status,200);assert.deepEqual(await response.json(),value);assert.equal(response.headers.get('cache-control'),'private, no-store');});assert.deepEqual(calls,['Bearer valid',{identity:{userId:'verified'},input:scope}]);});
test('amount route hides denial and malformed provider details',async()=>{for(const deps of [{authenticate:async()=>{throw Error('private token');},read:async()=>value},{authenticate:async()=>({userId:'verified'}),read:async()=>({...value,tenantId:'private tenant'})}])await server(deps,async url=>{const response=await fetch(`${url}?${new URLSearchParams(scope)}`,{headers:{authorization:'Bearer valid'}});assert.ok([403,503].includes(response.status));assert.doesNotMatch(await response.text(),/private|tenant|token|8600/);});});
const env={NIGHT_SCOUT_XERO_ACCOUNTING_READER_ENABLED:'true',NIGHT_SCOUT_RUNTIME_ENV:'staging',NIGHT_SCOUT_XERO_STAGING_PROJECT_REF:'bioalckltvkhlczusdvl',VITE_SUPABASE_URL:'https://bioalckltvkhlczusdvl.supabase.co',VITE_SUPABASE_ANON_KEY:'synthetic-public-key-material'};
const auth=()=>({auth:{getUser:async()=>({data:{user:{id:'verified-user'}},error:null})}});
test('runtime only forwards verified member bearer to fixed staging amount RPC, one request at a time',async()=>{let observed;const runtime=createXeroAccountingRuntime(env,{createAuthClient:auth,fetchImpl:async(url,options)=>{observed={url,options};return new Response(JSON.stringify(value));}});const identity=await runtime.authenticate('Bearer synthetic');assert.deepEqual(await runtime.read(identity,scope),value);assert.equal(observed.url,env.VITE_SUPABASE_URL+'/rest/v1/rpc/xero_accounting_period');assert.equal(observed.options.headers.authorization,'Bearer synthetic');assert.deepEqual(JSON.parse(observed.options.body),{p_store_id:scope.storeId,p_from:scope.from,p_to:scope.to,p_currency:scope.currency});await assert.rejects(runtime.read(identity,scope));assert.equal(createXeroAccountingRuntime({}),undefined);assert.throws(()=>createXeroAccountingRuntime({...env,NIGHT_SCOUT_RUNTIME_ENV:'production'}));});
test('runtime aborts undeclared oversized responses and rejects missing RPC without privileged fallback',async()=>{for(const response of [()=>new Response('x'.repeat(16_385)),()=>new Response('{}',{status:404}),()=>new Response(JSON.stringify({...value,storeId:'33333333-3333-4333-8333-333333333333'}))]){const runtime=createXeroAccountingRuntime(env,{createAuthClient:auth,fetchImpl:async()=>response()});await assert.rejects(runtime.read(await runtime.authenticate('Bearer synthetic'),scope));}});
