import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import http from 'node:http';
import {createXeroMappingRouter} from '../src/routes/xero-mappings.ts';
const storeId='10000000-0000-4000-8000-000000000001',connectionId='20000000-0000-4000-8000-000000000001';
const mapping={revenue:['sales'],processingFee:['fees'],advertising:['ads'],software:['software'],includedCash:['bank']};
async function server(deps,fn){const app=express();app.use('/mappings',createXeroMappingRouter(deps));const instance=http.createServer(app);await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});const request=async(path,{method='GET',body,authorization='Bearer trusted',type='application/json'}={})=>{const response=await fetch(`http://127.0.0.1:${instance.address().port}/mappings${path}`,{method,headers:{...(authorization?{authorization}:{}),...(method==='POST'?{'content-type':type}:{})},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)})});return {status:response.status,cache:response.headers.get('cache-control'),text:await response.text()};};try{await fn(request);}finally{await new Promise(resolve=>instance.close(resolve));}}
const deps=(overrides={})=>({authenticate:async token=>token==='Bearer trusted'?{userId:'alice',isOwner:true}:null,service:{readCurrentMapping:async()=>({safe:true}),confirmMapping:async()=>({safe:true})},...overrides});
test('router is disabled without both trusted dependencies',async()=>{for(const dependencies of [{},{service:deps().service},{authenticate:deps().authenticate}])await server(dependencies,async request=>{const response=await request(`/current?storeId=${storeId}&connectionId=${connectionId}`);assert.equal(response.status,503);assert.equal(response.cache,'no-store');});});
test('strict request validation stops calls before authentication or service',async()=>{let auth=0,calls=0;await server(deps({authenticate:async()=>{auth++;return {userId:'alice'};},service:{readCurrentMapping:async()=>{calls++;},confirmMapping:async()=>{calls++;}}}),async request=>{assert.equal((await request(`/current?storeId=${storeId}&connectionId=${connectionId}&tenantId=forged`)).status,400);assert.equal((await request('/confirm',{method:'POST',body:{storeId,connectionId,effectiveFrom:'2026-02-30',mapping}})).status,400);assert.equal((await request('/confirm',{method:'POST',body:{storeId,connectionId,effectiveFrom:'2026-09-18',mapping,actorId:'forged'}})).status,400);assert.equal((await request('/confirm',{method:'POST',body:{},type:'text/plain'})).status,415);assert.equal((await request('/confirm',{method:'POST',body:'{"bad":',type:'application/json'})).status,400);});assert.equal(auth,0);assert.equal(calls,0);});
test('authenticated current read and owner confirmation derive identity server-side',async()=>{const calls=[];await server(deps({service:{readCurrentMapping:async(identity,request)=>{calls.push(['read',identity,request]);return {mapping:'safe'};},confirmMapping:async(identity,request)=>{calls.push(['confirm',identity,request]);return {mapping:'safe'};}}}),async request=>{assert.equal((await request(`/current?storeId=${storeId}&connectionId=${connectionId}&asOf=2026-09-18`)).status,200);assert.equal((await request('/confirm',{method:'POST',body:{storeId,connectionId,effectiveFrom:'2026-09-18',mapping}})).status,200);});assert.deepEqual(calls[0][1],{userId:'alice',isOwner:true});assert.deepEqual(calls[1][1],{userId:'alice',isOwner:true});assert.equal(calls[1][2].tenantId,undefined);assert.equal(calls[1][2].confirmedBy,undefined);});
test('a non-owner may read but cannot confirm a mapping',async()=>{let confirmations=0;await server(deps({authenticate:async()=>({userId:'member',isOwner:false}),service:{readCurrentMapping:async()=>({safe:true}),confirmMapping:async()=>{confirmations++;return {safe:true};}}}),async request=>{assert.equal((await request(`/current?storeId=${storeId}&connectionId=${connectionId}`)).status,200);assert.equal((await request('/confirm',{method:'POST',body:{storeId,connectionId,effectiveFrom:'2026-09-18',mapping}})).status,403);});assert.equal(confirmations,0);});
test('authentication, access, service failures and absent mapping have fixed safe responses',async()=>{const secret='private-token';for(const [service,error,status] of [[{readCurrentMapping:async()=>null,confirmMapping:async()=>null},null,404],[{readCurrentMapping:async()=>{throw Error('Mapping access unavailable');},confirmMapping:async()=>{throw Error('Mapping access unavailable');}},'Mapping access unavailable',403],[{readCurrentMapping:async()=>{throw Error(`SQL ${secret}`);},confirmMapping:async()=>{throw Error(`SQL ${secret}`);}},`SQL ${secret}`,503]])await server(deps({service}),async request=>{const result=await request(`/current?storeId=${storeId}&connectionId=${connectionId}`);assert.equal(result.status,status);assert.ok(!result.text.includes(secret));});await server(deps(),async request=>assert.equal((await request(`/current?storeId=${storeId}&connectionId=${connectionId}`,{authorization:'Bearer denied'})).status,401));});
