import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {createXeroMerchantReadinessRouter} from '../src/routes/xero-merchant-readiness.ts';
import {cashReadinessFromMerchant} from '../src/lib/xero-cash-readiness.ts';
const store='11111111-1111-4111-8111-111111111111';
const view={storeId:store,connection:{status:'active',scopeVersion:'read-only-v1',createdAt:'2026-09-25T10:00:00Z',lastSuccessAt:'2026-09-25T12:00:00Z',lastFailureAt:null,mappingReviewRequired:false},evidenceState:'ready',evidenceRetrievedAt:'2026-09-25T12:00:00Z'};
async function server(deps,run){const app=express();app.use('/api/xero',createXeroMerchantReadinessRouter(deps));const instance=await new Promise(resolve=>{const value=app.listen(0,'127.0.0.1',()=>resolve(value));});try{await run(`http://127.0.0.1:${instance.address().port}/api/xero/cash-readiness`);}finally{await new Promise(resolve=>instance.close(resolve));}}
test('ready accounting remains incomplete cash and unsupported source fields cannot leak',()=>{const result=cashReadinessFromMerchant(view,store);assert.equal(result.state,'evidence_incomplete');assert.deepEqual(Object.keys(result).sort(),['detail','state','storeId']);for(const value of [{...view,amount:200},{...view,storeId:'22222222-2222-4222-8222-222222222222'},{...view,connection:{...view.connection,balance:300}}])assert.throws(()=>cashReadinessFromMerchant(value,store));for(const evidenceState of ['stale','review_required','denied'])assert.equal(cashReadinessFromMerchant({...view,evidenceState},store).state,evidenceState);assert.equal(cashReadinessFromMerchant({...view,connection:null,evidenceState:null,evidenceRetrievedAt:null},store).state,'not_connected');});
test('cash route reuses verified bearer member RPC and exact same-store context',async()=>{const calls=[];await server({authenticate:async auth=>{calls.push(auth);return {userId:'verified'};},service:{read:async(identity,id)=>{calls.push({identity,id});return view;}}},async url=>{const headers={authorization:'Bearer valid'};assert.equal((await fetch(`${url}?storeId=${store}`)).status,401);assert.equal((await fetch(`${url}?storeId=${store}&from=2026-09-01`,{headers})).status,400);const response=await fetch(`${url}?storeId=${store}`,{headers});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal((await response.json()).state,'evidence_incomplete');});assert.deepEqual(calls,['Bearer valid',{identity:{userId:'verified'},id:store}]);});
test('cash route disabled or denied never returns another store data or error details',async()=>{await server({},async url=>assert.equal((await fetch(`${url}?storeId=${store}`,{headers:{authorization:'Bearer valid'}})).status,503));for(const read of [async()=>{throw Error('private tenant token');},async()=>({...view,storeId:'22222222-2222-4222-8222-222222222222'})])await server({authenticate:async()=>({userId:'verified'}),service:{read}},async url=>{const response=await fetch(`${url}?storeId=${store}`,{headers:{authorization:'Bearer valid'}});assert.equal(response.status,403);assert.doesNotMatch(await response.text(),/tenant|token|22222222/);});});
