import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,cp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {prepareWorkerExport} from './prepare-export.mjs';
const source=fileURLToPath(new URL('../../',import.meta.url)),target='bioalckltvkhlczusdvl';
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'night-scout-worker-export-'));await mkdir(join(dir,'lib/db'),{recursive:true});for(const file of ['package.json','pnpm-workspace.yaml','.npmrc','pnpm-lock.yaml','lib/db/package.json'])await cp(join(source,file),join(dir,file));await cp(join(source,'deployments/nightly-staging/replit-worker.toml'),join(dir,'.replit'));return dir;}
test('narrows only exported workspace and installation policy; preserves manifests, catalogs and frozen lock',async()=>{const dir=await fixture();try{const names=['package.json','lib/db/package.json','pnpm-lock.yaml'],before=await Promise.all(names.map(n=>readFile(join(dir,n),'utf8')));const ws=await readFile(join(dir,'pnpm-workspace.yaml'),'utf8');await prepareWorkerExport(dir,target);const changed=await readFile(join(dir,'pnpm-workspace.yaml'),'utf8');assert.ok(changed.startsWith('packages:\n  - lib/db\n\n'));assert.equal(changed.slice(changed.indexOf('autoInstallPeers:')),ws.slice(ws.indexOf('autoInstallPeers:')));assert.deepEqual(await Promise.all(names.map(n=>readFile(join(dir,n),'utf8'))),before);const npm=await readFile(join(dir,'.npmrc'),'utf8');for(const value of ['production=true','ignore-scripts=true','frozen-lockfile=true','ci=true'])assert.ok(npm.includes(value));await prepareWorkerExport(dir,target);assert.equal(await readFile(join(dir,'.npmrc'),'utf8'),npm);}finally{await rm(dir,{recursive:true,force:true});}});
test('refuses unacknowledged, Git checkout and website exports before writes',async()=>{const dir=await fixture();try{await assert.rejects(prepareWorkerExport(dir,'wrong'),/confirmation/);await mkdir(join(dir,'.git'));await assert.rejects(prepareWorkerExport(dir,target),/Git checkout/);await rm(join(dir,'.git'),{recursive:true});await writeFile(join(dir,'.replit'),'deploymentTarget = "autoscale"');await assert.rejects(prepareWorkerExport(dir,target),/scheduled-worker/);assert.equal(await readFile(join(dir,'pnpm-workspace.yaml'),'utf8'),await readFile(join(source,'pnpm-workspace.yaml'),'utf8'));}finally{await rm(dir,{recursive:true,force:true});}});
