import test from 'node:test';
import assert from 'node:assert/strict';
import {createStagingXeroReportStructureDiagnostic} from './xero-report-structure-diagnostic.mjs';
import {encryptStagingEnvelope} from './xero-refresh-runtime.mjs';

const connectionId='11111111-1111-4111-8111-111111111111',mappingVersionId='22222222-2222-4222-8222-222222222222',tenantId='33333333-3333-4333-8333-333333333333',keyVersion='staging-v1';
const mapping={revenue:['sales'],processingFee:['fees'],advertising:['ads'],software:['software'],includedCash:['bank']};
const scopes='openid profile email accounting.settings.read accounting.reports.profitandloss.read accounting.reports.balancesheet.read accounting.reports.trialbalance.read accounting.reports.banksummary.read offline_access';
const env={NIGHT_SCOUT_RUNTIME_ENV:'staging',NIGHT_SCOUT_XERO_STAGING_REFRESH_ENABLED:'true',NIGHT_SCOUT_XERO_STAGING_PROJECT_REF:'bioalckltvkhlczusdvl',NIGHT_SCOUT_XERO_REPORT_FROM:'2026-09-01',NIGHT_SCOUT_XERO_REPORT_TO:'2026-09-25',NIGHT_SCOUT_XERO_CURRENCY:'GBP',NIGHT_SCOUT_INTAKE_DATABASE_URL:'postgresql://night_scout_import_login:password@db.bioalckltvkhlczusdvl.supabase.co:5432/postgres',NIGHT_SCOUT_STAGING_CA_PEM:`-----BEGIN CERTIFICATE-----\n${'A'.repeat(120)}\n-----END CERTIFICATE-----`,NIGHT_SCOUT_XERO_CLIENT_ID:'12345678-1234-1234-1234-123456789abc',NIGHT_SCOUT_XERO_CLIENT_SECRET:'x'.repeat(32),NIGHT_SCOUT_XERO_ENVELOPE_MASTER_KEY:'m'.repeat(43),NIGHT_SCOUT_XERO_ENVELOPE_KEY_VERSION:keyVersion};
const row=id=>({RowType:'Row',Cells:[{Value:'PRIVATE',Attributes:[{Id:'account',Value:id}]},{Value:'123.45'}]});
const response=(id,rows=[])=>new Response(JSON.stringify({Reports:[{ReportID:id,ReportName:'PRIVATE',ReportDate:'PRIVATE',Rows:rows}]}),{status:200});
function harness(){const envelope=encryptStagingEnvelope(env.NIGHT_SCOUT_XERO_ENVELOPE_MASTER_KEY,{connectionId,tenantId,keyVersion},'refresh-token-that-is-long-enough'),calls=[],lease=new Date(Date.now()+120_000).toISOString();const query=async(sql,params)=>{calls.push({sql,params});if(sql.includes('worker_get_single_connection_preflight_job'))return {rows:[{connection_id:connectionId,mapping_version_id:mappingVersionId}]};if(sql.includes('worker_get_refresh_context'))return {rows:[{connection_id:connectionId,tenant_id:tenantId,mapping_version_id:mappingVersionId,ciphertext:envelope.ciphertext,encrypted_dek:envelope.encryptedDek,key_version:keyVersion,algorithm:'AES-256-GCM',version:4,lease_expires_at:null,mapping}]};if(sql.includes('worker_acquire_refresh_lease'))return {rows:[{lease_expires_at:lease}]};if(sql.includes('worker_store_refresh_envelope_leased'))return {rows:[{rotated:true}]};if(sql.includes('worker_release_refresh_lease'))return {rows:[{released:true}]};throw Error('unexpected SQL');};const fetchImpl=async url=>{const value=String(url);if(value==='https://identity.xero.com/connect/token')return new Response(JSON.stringify({access_token:'access-token-that-is-long-enough',refresh_token:'next-refresh-token-that-is-long-enough',scope:scopes}),{status:200});if(value==='https://api.xero.com/connections')return new Response(JSON.stringify([{tenantId}]),{status:200});if(value.includes('/Organisation'))return new Response(JSON.stringify({Organisations:[{BaseCurrency:'GBP'}]}),{status:200});if(value.includes('ProfitAndLoss'))return response('ProfitAndLoss',[row('sales'),row('fees'),row('ads'),row('software')]);if(value.includes('BalanceSheet'))return response('BalanceSheet',[row('bank')]);if(value.includes('TrialBalance'))return response('TrialBalance');if(value.includes('BankSummary'))return response('BankSummary');throw Error('unexpected URL');};return {calls,query,fetchImpl,lease};}

test('rotates and releases credential but never selects or writes accounting evidence or retry authorization',async()=>{const h=harness(),result=await createStagingXeroReportStructureDiagnostic({env,query:h.query,fetchImpl:h.fetchImpl})();assert.equal(result.state,'observed');assert.deepEqual(result.reports.profitAndLoss.selected.revenue,{expected:1,found:1,missing:0,duplicate:0});const sql=h.calls.map(call=>call.sql).join('\n');assert.match(sql,/worker_get_single_connection_preflight_job/);assert.match(sql,/worker_store_refresh_envelope_leased/);assert.match(sql,/worker_release_refresh_lease/);assert.doesNotMatch(sql,/worker_get_single_refresh_job|accounting_evidence|retry_author/i);assert.deepEqual(h.calls.find(call=>call.sql.includes('worker_release_refresh_lease')).params,[connectionId,5,h.lease]);const output=JSON.stringify(result);for(const secret of [connectionId,tenantId,'sales','fees','ads','PRIVATE','123.45'])assert.doesNotMatch(output,new RegExp(secret.replace('.','\\.')));});
test('report HTTP failures are bounded and still release the rotated lease',async()=>{const h=harness(),fetchImpl=async url=>String(url).includes('ProfitAndLoss')?new Response('PRIVATE BODY',{status:429}):h.fetchImpl(url);const result=await createStagingXeroReportStructureDiagnostic({env,query:h.query,fetchImpl})();assert.deepEqual(result,{event:'xero_report_structure',state:'failed',phase:'profit_and_loss',reason:'rate_limited'});assert.equal(h.calls.filter(call=>call.sql.includes('worker_release_refresh_lease')).length,1);assert.doesNotMatch(JSON.stringify(result),/PRIVATE BODY/);});
